name: blocraft
description: CLI to scaffold Flutter Bloc Clean Architecture.
version: 1.1.0
homepage: https://github.com/singgiaditya/blocraft
repository: https://github.com/singgiaditya/blocraft
issue_tracker: https://github.com/singgiaditya/blocraft/issues

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

executables:
  blocraft: blocraft

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
